use crate::text_align::Style;
use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(
    name = "ascii-fmt",
    about = "Fix and align ASCII diagrams generated by AI agents",
    long_about = "ascii-fmt automatically fixes and aligns ASCII diagrams that AI agents generate incorrectly.

Common issues fixed:
  • Misaligned grid lines and boxes
  • Incorrect box-drawing symbols (+, -, | -> \u{253c}, \u{2500}, \u{2502})
  • Inconsistent spacing between elements
  • Broken table and tree structures

AI Agent Integration:
  1. Generate ASCII diagram with your AI agent
  2. Save output to file (e.g., diagram.txt)
  3. Run: ascii-fmt diagram.txt -o fixed_diagram.txt
  4. Use the corrected diagram in your documentation

Examples:
  ascii-fmt diagram.txt                    # Print to stdout
  ascii-fmt diagram.txt -o fixed.txt       # Save to file
  cat diagram.txt | ascii-fmt              # Read from stdin
  ascii-fmt diagram.txt --style detailed   # More aggressive fixes
  ascii-fmt diagram.txt --dry-run          # Preview changes
  ascii-fmt docs                           # Detailed documentation"
)]
#[command(version, propagate_version = true)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,

    #[arg(
        value_name = "INPUT",
        help = "Input file path. If omitted, reads from stdin. Supports .txt, .md, and any text file containing ASCII diagrams."
    )]
    pub input: Option<PathBuf>,

    #[arg(
        short,
        long,
        value_name = "FILE",
        help = "Output file path. If omitted, writes to stdout."
    )]
    pub output: Option<PathBuf>,

    #[arg(
        short,
        long,
        default_value_t = 2,
        help = "Target grid cell width (in characters). Higher values = wider cells. Recommended: 2-4"
    )]
    pub width: usize,

    #[arg(
        short,
        long,
        default_value = "standard",
        value_parser = clap::value_parser!(StyleStr),
        help = "Formatting style preset:

  minimal    - Only critical fixes, minimal changes
  standard   - Balanced fixes (recommended for AI output)
  detailed   - Maximum fixes, centering, validation"
    )]
    pub style: StyleStr,

    #[arg(
        long,
        default_value_t = true,
        help = "Fix box-drawing symbols (+, -, | -> \u{253c}, \u{2500}, \u{2502}, etc.)"
    )]
    pub fix_box_drawing: bool,

    #[arg(
        long,
        default_value_t = true,
        help = "Normalize whitespace and spacing"
    )]
    pub fix_whitespace: bool,

    #[arg(
        long,
        default_value_t = true,
        help = "Preserve empty lines in the output"
    )]
    pub preserve_empty_lines: bool,

    #[arg(
        long,
        help = "Show formatted output without writing to file (useful for previewing)"
    )]
    pub dry_run: bool,

    #[arg(short, long, action = clap::ArgAction::Count, help = "Verbose output (-v, -vv for more details)")]
    pub verbose: u8,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    /// Show detailed documentation and examples for AI agent integration
    Docs {
        /// Show specific topic: 'examples', 'api', 'integration', 'file-formats'
        topic: Option<String>,
    },

    /// Install OpenCode plugin for auto-formatting ASCII diagrams on file edits
    OpencodeSetup {
        /// Overwrite existing OpenCode plugin file if present
        #[arg(long, default_value_t = false)]
        force: bool,

        /// Install into the current project (.opencode/plugins/) instead of global OpenCode config (~/.config/opencode/plugins/)
        #[arg(long, default_value_t = false)]
        project: bool,
    },
}

#[derive(Debug, Clone, clap::ValueEnum)]
pub enum StyleStr {
    Minimal,
    Standard,
    Detailed,
}

impl From<StyleStr> for Style {
    fn from(style: StyleStr) -> Self {
        match style {
            StyleStr::Minimal => Style::Minimal,
            StyleStr::Standard => Style::Standard,
            StyleStr::Detailed => Style::Detailed,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Options {
    pub width: usize,
    pub style: Style,
    pub fix_box_drawing: bool,
    pub fix_whitespace: bool,
    pub preserve_empty_lines: bool,
    pub dry_run: bool,
    pub verbose: bool,
}

impl TryFrom<Cli> for Options {
    type Error = String;

    fn try_from(cli: Cli) -> std::result::Result<Self, Self::Error> {
        let style: Style = cli.style.into();

        Ok(Options {
            width: cli.width,
            style,
            fix_box_drawing: cli.fix_box_drawing,
            fix_whitespace: cli.fix_whitespace,
            preserve_empty_lines: cli.preserve_empty_lines,
            dry_run: cli.dry_run,
            verbose: cli.verbose > 0,
        })
    }
}

impl Default for Options {
    fn default() -> Self {
        Options {
            width: 2,
            style: Style::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_options_clone() {
        let options = Options {
            width: 4,
            style: Style::Detailed,
            fix_box_drawing: false,
            fix_whitespace: true,
            preserve_empty_lines: false,
            dry_run: true,
            verbose: true,
        };

        let options_clone = options.clone();
        assert_eq!(options_clone.width, 4);
        assert_eq!(options_clone.style, Style::Detailed);
        assert_eq!(options_clone.fix_box_drawing, false);
        assert_eq!(options_clone.fix_whitespace, true);
        assert_eq!(options_clone.preserve_empty_lines, false);
        assert_eq!(options_clone.dry_run, true);
        assert_eq!(options_clone.verbose, true);
    }

    #[test]
    fn test_options_default() {
        let options = Options::default();
        assert_eq!(options.width, 2);
        assert_eq!(options.style, Style::Standard);
        assert_eq!(options.fix_box_drawing, true);
        assert_eq!(options.fix_whitespace, true);
        assert_eq!(options.preserve_empty_lines, true);
        assert_eq!(options.dry_run, false);
        assert_eq!(options.verbose, false);
    }

    #[test]
    fn test_options_debug() {
        let options = Options::default();
        let _ = format!("{:?}", options);
    }

    #[test]
    fn test_style_equality() {
        assert_eq!(Style::Minimal, Style::Minimal);
        assert_eq!(Style::Standard, Style::Standard);
        assert_eq!(Style::Detailed, Style::Detailed);
        assert_ne!(Style::Minimal, Style::Standard);
        assert_ne!(Style::Standard, Style::Detailed);
    }

    #[test]
    fn test_style_copy_and_clone() {
        let style = Style::Standard;
        let style_copy = style;
        assert_eq!(style, style_copy);
        let style_clone = style.clone();
        assert_eq!(style, style_clone);
    }

    #[test]
    fn test_options_from_cli_valid_minimal() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Minimal,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options: Result<Options, String> = cli.try_into();
        assert!(options.is_ok());
        let options = options.unwrap();
        assert_eq!(options.style, Style::Minimal);
    }

    #[test]
    fn test_options_from_cli_valid_standard() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options: Result<Options, String> = cli.try_into();
        assert!(options.is_ok());
        let options = options.unwrap();
        assert_eq!(options.style, Style::Standard);
    }

    #[test]
    fn test_options_from_cli_valid_detailed() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Detailed,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options: Result<Options, String> = cli.try_into();
        assert!(options.is_ok());
        let options = options.unwrap();
        assert_eq!(options.style, Style::Detailed);
    }

    #[test]
    fn test_options_from_cli_case_insensitive() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Minimal,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options: Result<Options, String> = cli.try_into();
        assert!(options.is_ok());
        assert_eq!(options.unwrap().style, Style::Minimal);
    }

    #[test]
    fn test_options_from_cli_mixed_case() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options: Result<Options, String> = cli.try_into();
        assert!(options.is_ok());
        assert_eq!(options.unwrap().style, Style::Standard);
    }

    #[test]
    fn test_options_preserves_width() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 5,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.width, 5);
    }

    #[test]
    fn test_options_preserves_boolean_flags() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: false,
            fix_whitespace: false,
            preserve_empty_lines: false,
            dry_run: true,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.fix_box_drawing, false);
        assert_eq!(options.fix_whitespace, false);
        assert_eq!(options.preserve_empty_lines, false);
        assert_eq!(options.dry_run, true);
    }

    #[test]
    fn test_options_verbose_count() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 2,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.verbose, true);
    }

    #[test]
    fn test_options_verbose_zero() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.verbose, false);
    }

    #[test]
    fn test_options_all_flags_true() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert!(options.fix_box_drawing);
        assert!(options.fix_whitespace);
        assert!(options.preserve_empty_lines);
        assert!(!options.dry_run);
        assert!(!options.verbose);
    }

    #[test]
    fn test_options_all_flags_false() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: false,
            fix_whitespace: false,
            preserve_empty_lines: false,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert!(!options.fix_box_drawing);
        assert!(!options.fix_whitespace);
        assert!(!options.preserve_empty_lines);
        assert!(!options.dry_run);
        assert!(!options.verbose);
    }

    #[test]
    fn test_options_detailed_style() {
        let cli = Cli {
            command: None,
            input: None,
            output: None,
            width: 4,
            style: StyleStr::Detailed,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.style, Style::Detailed);
        assert_eq!(options.width, 4);
    }

    #[test]
    fn test_options_with_command() {
        let cli = Cli {
            command: Some(Commands::Docs {
                topic: Some("examples".to_string()),
            }),
            input: None,
            output: None,
            width: 2,
            style: StyleStr::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: 0,
        };

        let options = Options::try_from(cli).unwrap();
        assert_eq!(options.style, Style::Standard);
        assert_eq!(options.width, 2);
    }

    #[test]
    fn test_style_str_from_into() {
        assert_eq!(Style::from(StyleStr::Minimal), Style::Minimal);
        assert_eq!(Style::from(StyleStr::Standard), Style::Standard);
        assert_eq!(Style::from(StyleStr::Detailed), Style::Detailed);
    }
}
