use crate::text_align::Style;
use clap::Parser;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(name = "ascii-fmt")]
#[command(about = "CLI tool to fix and align ASCII diagrams generated by AI agents", long_about = None)]
pub struct Cli {
    #[arg(value_name = "INPUT")]
    pub input: Option<PathBuf>,

    #[arg(short, long, value_name = "FILE")]
    pub output: Option<PathBuf>,

    #[arg(short, long, default_value_t = 2)]
    pub width: usize,

    #[arg(short, long, default_value = "standard")]
    pub style: String,

    #[arg(long, default_value_t = true)]
    pub fix_box_drawing: bool,

    #[arg(long, default_value_t = true)]
    pub fix_whitespace: bool,

    #[arg(long, default_value_t = true)]
    pub preserve_empty_lines: bool,

    #[arg(long)]
    pub dry_run: bool,

    #[arg(short, long, action = clap::ArgAction::Count)]
    pub verbose: u8,
}

#[derive(Debug, Clone)]
pub struct Options {
    pub width: usize,
    pub style: Style,
    pub fix_box_drawing: bool,
    pub fix_whitespace: bool,
    pub preserve_empty_lines: bool,
    pub dry_run: bool,
    pub verbose: bool,
}

impl TryFrom<Cli> for Options {
    type Error = String;

    fn try_from(cli: Cli) -> std::result::Result<Self, Self::Error> {
        let style = match cli.style.to_lowercase().as_str() {
            "minimal" => Style::Minimal,
            "standard" => Style::Standard,
            "detailed" => Style::Detailed,
            _ => return Err(format!("Invalid style: {}. Must be one of: minimal, standard, detailed", cli.style)),
        };

        Ok(Options {
            width: cli.width,
            style,
            fix_box_drawing: cli.fix_box_drawing,
            fix_whitespace: cli.fix_whitespace,
            preserve_empty_lines: cli.preserve_empty_lines,
            dry_run: cli.dry_run,
            verbose: cli.verbose > 0,
        })
    }
}

impl Default for Options {
    fn default() -> Self {
        Options {
            width: 2,
            style: Style::Standard,
            fix_box_drawing: true,
            fix_whitespace: true,
            preserve_empty_lines: true,
            dry_run: false,
            verbose: false,
        }
    }
}
