use ascii_fmt::error::Result;
use clap::Parser;
use std::io::Read;

fn main() -> Result<()> {
    let cli = ascii_fmt::cli::Cli::parse();

    if let Some(command) = cli.command {
        handle_command(command)?;
        return Ok(());
    }

    let input_path = cli.input.clone();
    let output_path = cli.output.clone();
    let options: ascii_fmt::cli::Options = cli
        .try_into()
        .map_err(ascii_fmt::error::Error::InvalidInput)?;

    if options.verbose {
        eprintln!("ascii-fmt v{}", env!("CARGO_PKG_VERSION"));
        eprintln!("Options: {:?}", options);
    }

    let input = read_input(input_path)?;

    if options.verbose {
        eprintln!("Input: {} lines", input.lines().count());
    }

    let output = ascii_fmt::formatter::format_ascii(&input, &options)?;

    if options.dry_run {
        eprintln!("--- Dry run: showing formatted output ---");
        println!("{}", output);
        eprintln!("--- End of dry run ---");
    } else {
        write_output(output_path, &output)?;
    }

    Ok(())
}

fn handle_command(command: ascii_fmt::cli::Commands) -> Result<()> {
    match command {
        ascii_fmt::cli::Commands::Docs { topic } => {
            print_help(topic);
        }
        ascii_fmt::cli::Commands::OpencodeSetup { force, project } => {
            install_opencode_plugin(force, project)?;
        }
    }
    Ok(())
}

fn install_opencode_plugin(force: bool, project: bool) -> Result<()> {
    let plugin_dir = if project {
        // Project-level plugin.
        let cwd = std::env::current_dir().map_err(ascii_fmt::error::Error::Io)?;
        cwd.join(".opencode").join("plugins")
    } else {
        // Global plugin.
        resolve_opencode_config_dir()?.join("plugins")
    };
    let plugin_path = plugin_dir.join("ascii-fmt.js");

    std::fs::create_dir_all(&plugin_dir).map_err(ascii_fmt::error::Error::Io)?;

    if plugin_path.exists() && !force {
        eprintln!(
            "OpenCode plugin already exists: {}\nRe-run with --force to overwrite.",
            plugin_path.display()
        );
        return Ok(());
    }

    // Keep the plugin source in-repo and embed it into the binary.
    const PLUGIN: &str = include_str!("../scripts/opencode-plugin.js");
    std::fs::write(&plugin_path, PLUGIN).map_err(ascii_fmt::error::Error::Io)?;

    eprintln!("Installed OpenCode plugin: {}", plugin_path.display());
    eprintln!("Markdown fenced blocks supported: ```ascii, ```diagram, ```ascii-diagram");

    Ok(())
}

fn resolve_opencode_config_dir() -> Result<std::path::PathBuf> {
    // Follow OpenCode config docs:
    // - Global config: ~/.config/opencode/opencode.json
    // - Global plugins: ~/.config/opencode/plugins/
    // Also respect OPENCODE_CONFIG_DIR when set.
    if let Some(dir) = std::env::var_os("OPENCODE_CONFIG_DIR") {
        return Ok(expand_tilde(std::path::PathBuf::from(dir)));
    }

    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        return Ok(std::path::PathBuf::from(xdg).join("opencode"));
    }

    let home = home_dir().ok_or_else(|| {
        ascii_fmt::error::Error::InvalidInput(
            "Could not determine home directory for global OpenCode install".to_string(),
        )
    })?;

    Ok(home.join(".config").join("opencode"))
}

fn home_dir() -> Option<std::path::PathBuf> {
    std::env::var_os("HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| std::env::var_os("USERPROFILE").map(std::path::PathBuf::from))
}

fn expand_tilde(path: std::path::PathBuf) -> std::path::PathBuf {
    let s = path.to_string_lossy();
    if s == "~" {
        return home_dir().unwrap_or(path);
    }

    if let Some(rest) = s.strip_prefix("~/") {
        return match home_dir() {
            Some(home) => home.join(rest),
            None => path,
        };
    }

    if let Some(rest) = s.strip_prefix("~\\") {
        return match home_dir() {
            Some(home) => home.join(rest),
            None => path,
        };
    }

    path
}

fn print_help(topic: Option<String>) {
    match topic.as_deref() {
        Some("examples") => print_examples_help(),
        Some("api") => print_api_help(),
        Some("integration") => print_integration_help(),
        Some("file-formats") => print_file_formats_help(),
        Some(_) | None => print_general_help(),
    }
}

fn print_general_help() {
    println!("ascii-fmt - Fix and align ASCII diagrams generated by AI agents\n");
    println!("QUICK START:");
    println!("  ascii-fmt diagram.txt                # Print to stdout");
    println!("  ascii-fmt diagram.txt -o fixed.txt   # Save to file\n");
    println!("AI AGENT WORKFLOW:");
    println!("  1. Generate ASCII diagram with your AI agent");
    println!("  2. Save output to file: echo \"$AI_OUTPUT\" > diagram.txt");
    println!("  3. Fix formatting: ascii-fmt diagram.txt -o diagram_fixed.txt");
    println!("  4. Use fixed diagram in your documentation\n");
    println!("DIAGRAM TYPES SUPPORTED:");
    println!("  • Flowcharts - Arrows, decision blocks");
    println!("  • Trees - Hierarchical structures");
    println!("  • Architecture - Layered systems");
    println!("  • Sequence - Vertical timelines");
    println!("  • Tables - ASCII tables with borders\n");
    println!("COMMON ISSUES FIXED:");
    println!("  • Misaligned grid lines and boxes");
    println!("  • Incorrect box-drawing symbols (+, -, | → ┼, ─, │)");
    println!("  • Inconsistent spacing between elements");
    println!("  • Broken table and tree structures\n");
    println!("USAGE:");
    println!("  ascii-fmt [INPUT] [OPTIONS]");
    println!("  ascii-fmt docs [TOPIC]");
    println!("  ascii-fmt docs examples     # Show usage examples");
    println!("  ascii-fmt docs integration  # AI agent integration guide");
    println!("  ascii-fmt docs file-formats # Supported file formats\n");
    println!("For more information, run: ascii-fmt docs [topic]");
}

fn print_examples_help() {
    println!("USAGE EXAMPLES\n");
    println!("1. BASIC FORMATTING");
    println!("   ascii-fmt diagram.txt\n");
    println!("   Output: Formatted diagram printed to stdout\n");

    println!("2. SAVE TO FILE");
    println!("   ascii-fmt diagram.txt -o fixed_diagram.txt\n");
    println!("   Output: Saves formatted diagram to fixed_diagram.txt\n");

    println!("3. READ FROM STDIN");
    println!("   cat diagram.txt | ascii-fmt > output.txt\n");
    println!("   Output: Reads from stdin, writes to output.txt\n");

    println!("4. PIPE FROM AI AGENT");
    println!("   echo \"$AI_RESPONSE\" | ascii-fmt > diagram.txt\n");
    println!("   Output: Pipes AI output directly to formatter\n");

    println!("5. DETAILED FORMATTING");
    println!("   ascii-fmt diagram.txt --style detailed\n");
    println!("   Output: Aggressive fixes with centering and validation\n");

    println!("6. CUSTOM CELL WIDTH");
    println!("   ascii-fmt diagram.txt --width 4\n");
    println!("   Output: Uses wider grid cells (4 chars)\n");

    println!("7. PREVIEW CHANGES");
    println!("   ascii-fmt diagram.txt --dry-run\n");
    println!("   Output: Shows formatted output without writing file\n");

    println!("8. MINIMAL FIXES ONLY");
    println!("   ascii-fmt diagram.txt --style minimal\n");
    println!("   Output: Only critical fixes, minimal changes\n");

    println!("9. DISABLE SPECIFIC FIXES");
    println!("   ascii-fmt diagram.txt --no-fix-box-drawing\n");
    println!("   Output: Fix spacing but keep original symbols\n");

    println!("10. MULTIPLE FILES (bash)");
    println!("    for f in *.txt; do ascii-fmt \"$f\" -o \"fixed_$f\"; done\n");
    println!("    Output: Formats all .txt files with 'fixed_' prefix\n");

    println!("11. INLINE IN MARKDOWN");
    println!("    sed '/```diagram/,/```/{{/```/!s/^/  /}}' README.md |\n");
    println!("      ascii-fmt -o README_fixed.md\n");
    println!("   Output: Formats diagram blocks in markdown\n");

    println!("12. COMBINE WITH OTHER TOOLS");
    println!("    cat diagram.txt | ascii-fmt | less\n");
    println!("   Output: View formatted output in pager\n");
}

fn print_api_help() {
    println!("API REFERENCE\n");
    println!("COMMANDS:");
    println!("  ascii-fmt [INPUT] [OPTIONS]   Format ASCII diagram");
    println!("  ascii-fmt help [TOPIC]         Show help topics\n");

    println!("ARGUMENTS:");
    println!("  INPUT                         Input file path (optional)");
    println!("                                If omitted, reads from stdin\n");

    println!("OPTIONS:");
    println!("  -o, --output <FILE>          Output file path");
    println!("                                If omitted, writes to stdout");
    println!("  -w, --width <N>              Target grid cell width [default: 2]");
    println!("                                Recommended: 2-4");
    println!("  -s, --style <STYLE>          Style preset:");
    println!("                                minimal   - Only critical fixes");
    println!("                                standard  - Balanced fixes (default)");
    println!("                                detailed  - Maximum fixes");
    println!("      --fix-box-drawing         Fix box-drawing symbols [default: true]");
    println!("      --fix-whitespace          Normalize whitespace [default: true]");
    println!("      --preserve-empty-lines     Preserve empty lines [default: true]");
    println!("      --dry-run                Preview changes without writing");
    println!("  -v, --verbose               Verbose output (use -vv for more)");
    println!("  -h, --help                  Show help");
    println!("  -V, --version               Show version\n");

    println!("EXIT CODES:");
    println!("  0                            Success");
    println!("  1                            Error (invalid input, I/O error)\n");

    println!("ENVIRONMENT:");
    println!("  LANG, LC_ALL                 Locale for Unicode support");
    println!("                                UTF-8 recommended");
}

fn print_integration_help() {
    println!("AI AGENT INTEGRATION GUIDE\n");
    println!("RECOMMENDED WORKFLOW:\n");
    println!("1. GENERATE DIAGRAM");
    println!("   Ask your AI agent: 'Generate an ASCII flowchart showing X'\n");

    println!("2. SAVE RAW OUTPUT");
    println!("   $ echo \"$AI_RESPONSE\" > diagram.txt\n");
    println!("   Or use your AI tool's save functionality\n");

    println!("3. FORMAT DIAGRAM");
    println!("   $ ascii-fmt diagram.txt -o diagram_fixed.txt\n");
    println!("   This fixes common AI mistakes:\n");
    println!("   • Misaligned grid lines");
    println!("   • Incorrect box-drawing symbols");
    println!("   • Inconsistent spacing\n");

    println!("4. USE FORMATTED DIAGRAM");
    println!("   Insert diagram_fixed.txt into your documentation\n");

    println!("AUTOMATION EXAMPLES:\n");
    println!("SHELL SCRIPT (bash):");
    println!("   #!/bin/bash");
    println!("   ai_agent \"$1\" | ascii-fmt > diagram.txt\n");
    println!("   # Usage: ./generate_diagram.sh 'Create a flowchart'\n");

    println!("PYTHON:");
    println!("   import subprocess");
    println!("   import textwrap\n");
    println!("   def format_diagram(ai_output):");
    println!("       result = subprocess.run(");
    println!("           ['ascii-fmt'],");
    println!("           input=ai_output,");
    println!("           capture_output=True,");
    println!("           text=True");
    println!("       )");
    println!("       return result.stdout\n");

    println!("NODE.JS:");
    println!("   const {{ execSync }} = require('child_process');");
    println!("   const formatDiagram = (diagram) => {{");
    println!("       return execSync('ascii-fmt', {{ input: diagram }}).toString();");
    println!("   }};\n");

    println!("BEST PRACTICES:\n");
    println!("1. Always verify output after formatting");
    println!("2. Use --dry-run to preview changes before saving");
    println!("3. Try different styles if output is not perfect:");
    println!("   - minimal for minor issues");
    println!("   - standard for typical AI output");
    println!("   - detailed for complex diagrams");
    println!("4. For large diagrams, consider --width 3 or 4");
    println!("5. Preserve original AI output for comparison\n");

    println!("TROUBLESHOOTING:\n");
    println!("Issue: Diagram not fixed correctly");
    println!("Solution: Try different styles");
    println!("  $ ascii-fmt diagram.txt --style minimal");
    println!("  $ ascii-fmt diagram.txt --style detailed\n");

    println!("Issue: Encoding problems");
    println!("Solution: Ensure UTF-8 locale");
    println!("  $ export LANG=en_US.UTF-8\n");

    println!("Issue: Performance on large files");
    println!("Solution: Use release build");
    println!("  $ cargo install --release ascii-fmt\n");
}

fn print_file_formats_help() {
    println!("SUPPORTED FILE FORMATS\n");
    println!("TEXT FILES (.txt):");
    println!("  • Most common format for ASCII diagrams");
    println!("  • Works with any text editor");
    println!("  Example: ascii-fmt diagram.txt\n");

    println!("MARKDOWN FILES (.md):");
    println!("  • Supports diagrams in code blocks");
    println!("  • Preserve formatting in documentation");
    println!("  Example: ascii-fmt README.md > README_fixed.md\n");
    println!("  Or format specific blocks:");
    println!("  $ sed -n '/```diagram/,/```/p' README.md | ascii-fmt\n");

    println!("CODE FILES (.rs, .py, .js, etc.):");
    println!("  • Format diagrams in code comments");
    println!("  • Works with any programming language");
    println!("  Example: ascii-fmt main.rs > main_fixed.rs\n");

    println!("STANDARD INPUT (stdin):");
    println!("  • Read from pipe or redirection");
    println!("  • Useful for integration with other tools");
    println!("  Examples:");
    println!("    $ cat diagram.txt | ascii-fmt");
    println!("    $ echo \"$DIAGRAM\" | ascii-fmt");
    println!("    $ ai_agent | ascii-fmt > output.txt\n");

    println!("ANY PLAIN TEXT FILE:");
    println!("  • ascii-fmt works with any plain text");
    println!("  • It detects ASCII diagrams automatically");
    println!("  • Non-diagram content is preserved\n");

    println!("ENCODING:");
    println!("  • UTF-8 encoding is required");
    println!("  • Ensure your terminal/files support UTF-8");
    println!("  • Box-drawing symbols require Unicode support\n");

    println!("FILE SIZE LIMITS:");
    println!("  • No hardcoded limits");
    println!("  • Performance scales with file size");
    println!("  • <1000 lines: Instant (ms)");
    println!("  • 1000-10000 lines: Fast (<1s)");
    println!("  • >10000 lines: May take several seconds\n");

    println!("MULTIPLE DIAGRAMS IN ONE FILE:");
    println!("  • ascii-fmt handles multiple diagrams");
    println!("  • Each diagram is formatted independently");
    println!("  • Empty lines separate diagrams");
    println!("  Example:");
    println!("    $ ascii-fmt multi_diagram.txt\n");

    println!("OUTPUT FORMATS:");
    println!("  • stdout: Print to terminal");
    println!("  • file: Save with -o option");
    println!("  • pipe: Chain with other commands");
    println!("  Example:");
    println!("    $ ascii-fmt diagram.txt | tee output.txt | less\n");
}

fn read_input(path: Option<std::path::PathBuf>) -> Result<String> {
    match path {
        Some(p) => std::fs::read_to_string(&p).map_err(ascii_fmt::error::Error::Io),
        None => {
            let mut buffer = String::new();
            std::io::stdin()
                .read_to_string(&mut buffer)
                .map_err(ascii_fmt::error::Error::Io)?;
            Ok(buffer)
        }
    }
}

fn write_output(path: Option<std::path::PathBuf>, content: &str) -> Result<()> {
    match path {
        Some(p) => {
            std::fs::write(&p, content).map_err(ascii_fmt::error::Error::Io)?;
            Ok(())
        }
        None => {
            print!("{}", content);
            Ok(())
        }
    }
}
